server:
  port: 8080
  servlet:
    context-path: /api
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
logging:
  level:
    ROOT: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE